"""Added tables

Revision ID: adf84aefcd7d
Revises: 
Create Date: 2022-08-13 06:00:13.957070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf84aefcd7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_user_id', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.String(length=64), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('bill_amount', sa.Float(), nullable=True),
    sa.Column('admin_ch', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_operations')
    op.drop_table('block_users')
    # ### end Alembic commands ###
